version: '3.3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    ports:
      - 3000:3000
