name: ci

on:
  push:
    branches:
      - 'master'

env:
  APP_NAME: orchid-server
  APP_BRANCH: master
  APP_REPO_GITOPS: git@github.com:baroxdev/orchid-world-backend.git

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ env.APP_NAME }}:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ github.actor }}/${{ env.APP_NAME }}:${{ github.sha }}
            docker stop $(docker ps -q) || true
            docker run -d -p 80:80 ghcr.io/${{ github.actor }}/${{ env.APP_NAME }}:${{ github.sha }}
